# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src ./src

# Install dependencies and the package
RUN pip install --no-cache-dir .

# Set the entrypoint for the MCP server (stdio transport)
ENTRYPOINT ["python", "-m", "bangla_news_mcp"]
